#!/bin/bash
echo 'Update installer v1.1'
CONF_DIR=/etc/raspi-setup/update
REPO=raspbian-joshun
SCRIPTS="$CONF_DIR/$REPO/scripts"
cp "$SCRIPTS/raspi-setup" /usr/bin
cp "$SCRIPTS/desktop-setup" /usr/bin
cp "$SCRIPTS/update-scripts" /usr/bin
cp "$SCRIPTS/initial-boot" /etc/raspi-setup
echo 'Scripts updated.'