#!/bin/bash
CONFIGDIR=/etc/raspi-setup
printmenu()
{
        args=("$@")
        count=1
        end=$(($# + 1))
        while [ "$count" -lt "$end" ];
        do
                echo "$count: ${args[$(($count - 1))]}"
                count=$((count + 1))
        done
}
selectchoice()
{
        choice=""
        echo ""
        read -e -n 1 -p '?  ' choice
}
anykey()
{
         echo 'Press any key to continue.'
         read -n 1
}
do_install()
{
	echo 'Packages will now be installed. You will be asked for you password.'
	anykey
	echo 'Refreshing package lists...'
	sudo apt-get update
	echo 'Running install...'
	sudo apt-get install -y $termem $webbrowse $office $music $ide $archive $fileman
	if [ "$packages" = "" ]; then echo 'No custom packages'; else sudo apt-get install -y $packages; fi
	sudo rm -f $CONFIGDIR/wizardrun
	echo 'Install completed.'
	anykey

}
custompac()
{
	clear
	echo 'Enter additional packages below, leave blank for none:'
	read -e packages
	do_install
}
filemanager()
{
	clear
	echo 'Choose File Manager:'
	printmenu "thunar" "pcmanfm" "mc" "rox-filer" "skip"
	selectchoice
	case $choice in
		1 ) fileman=thunar ;;
		2 ) fileman=pcmanfm ;;
		3 ) fileman=mc ;;
		4 ) fileman=rox-filer ;;
		5 ) fileman="" ;;
		* ) filemanager ;;
	esac
	custompac
}
archiver()
{
	clear
	echo 'Choose Archiver:'
	printmenu "xarchiver" "squeeze" "skip"
	selectchoice
	case $choice in
		1 ) archive=xarchiver ;;
		2 ) archive=squeeze ;;
		3 ) archive="" ;;
		* ) archiver
	esac
	filemanager
}
ideselect()
{
	clear
	echo 'Choose IDE / Text Editor'
	printmenu "geany" "codeblocks" "idle (python)" "bluefish" "leafpad" "skip"
	selectchoice
	case $choice in
		1 ) ide=geany ;;
		2 ) ide=codeblocks ;;
		3 ) ide=idle ;;
		4 ) ide=bluefish ;;
		5 ) ide=leafpad ;;
		6 ) ide="" ;;
		* ) ideselect ;;
	esac
	archiver
}
multimedia()
{
	clear
	echo 'Choose music player:'
	printmenu "gmusicbrowser" "audacious" "gxmms2" "decibel-audio-player" "opencubicplayer" "moc" "skip"
	selectchoice
	case $choice in
		1 ) music=gmusicbrowser ;;
		2 ) music=audacious ;;
		3 ) music=gxmms2 ;;
		4 ) music=decibel-audio-player ;;
		5 ) music=opencubicplayer ;;
		6 ) music=moc ;;
		7 ) music="" ;;
		* ) multimedia ;;
	esac
	ideselect
}
emailapp()
{
	clear
	echo 'Choose email program:'
	printmenu "claws-mail" "sylpheed" "balsa" "skip"
	selectchoice
	case $choice in
		1 ) email=claws-mail ;;
		2 ) email=sylpheed ;;
		3 ) email=balsa ;;
		4 ) email="" ;;
		* ) emailapp ;;
	esac
	multimedia
}
officesuite()
{
	clear
	echo 'Choose office suite apps:'
	printmenu "abiword" "gnumeric" "both" "skip"
	selectchoice
	case $choice in
		1 ) office=abiword ;;
		2 ) office=gnumeric ;;
		3 ) office='abiword gnumeric' ;;
		4 ) office="" ;;
		* ) officesuite ;;
	esac
	emailapp
}
webbrowser()
{
	clear
	echo 'Choose web browser:'
	printmenu "midori" "arora" "netsurf" "galeon" "links" "links2" "lynx" "w3m" "skip"
	selectchoice
	case $choice in
		1 ) webbrowse=midori ;;
		2 ) webbrowse=arora ;;
		3 ) webbrowse=netsurf ;;
		4 ) webbrowse=galeon ;;
		5 ) webbrowse=links ;;
		6 ) webbrowse=links2 ;;
		7 ) webbrowse=lynx ;;
		8 ) webbrowse=w3m ;;
		9 ) webbrowse="" ;;
		* ) webbrowser ;;
	esac
	officesuite
}
runwizard()
{
	clear
	echo 'Note: The wizard will ask if you want to install other packages later.'
	echo 'Choose terminal application:'
	printmenu "rxvt-unicode" "lxterminal" "xfce4-terminal" "guake" "terminator" "skip"
	selectchoice
	case $choice in
		1 ) termem=rxvt-unicode ;;
		2 ) termem=lxterminal ;;
		3 ) termem=xfce4-terminal ;;
		4 ) termem=guake ;;
		5 ) termem=terminator ;;
		6 ) termem="" ;;
		* ) runwizard ;;
	esac
	webbrowser
}
yesno()
{
        echo '1: Yes 2: No'
}
anykey()
{
                echo 'Press any key to continue.'
                read -n 1
}

initial()
{
	clear
	echo 'This wizard will guide you through installing desktop software'
	printmenu "Continue" "Cancel" "Cancel and don't run again"
	selectchoice
	case $choice in
		1 ) runwizard ;;
		2 ) exit ;;
		3 ) sudo rm -f $CONFIGDIR/wizardrun; exit ;;
		* ) initial ;;
	esac
}
initial
