#!/bin/bash
UPDATE_URI=git://github.com/Joshun/raspbian-joshun.git
CONF_DIR=/home/joshua/Desktop/testgit
STORE="$CONF_DIR/update_revision"
REPO=raspbian-joshun
newline()
{
echo ''
}
if [ ! -d "$CONF_DIR/$REPO" ]; then touch "$STORE"; echo 'Running for the first time'; cd "$CONF_DIR"; git clone "$UPDATE_URI"; else cd "$CONF_DIR"; fi
CURRENT=`cat "$STORE"`
cd "$CONF_DIR/$REPO"
git pull "$UPDATE_URI"
VERSION=`git rev-list HEAD | tail -1`
if [ "$VERSION" != "$CURRENT" ];
then
newline
echo '===Updates will now be installed==='
./install_updates
if [ "$?" = "0" ]; then echo "$VERSION" > "$STORE"; fi
else
newline
echo '===No updates available==='
fi